### PR TITLE
x11: include wm_instance

### PR DESCRIPTION
**Pull request by powellnorma**
Can be useful

### CODE REVIEW

**Comment by 2e3s** [comment]
Hello, thanks for the suggestions! I think it would be better to have https://github.com/2e3s/awatcher/pull/28/commits/9daebc85c0f81c4e450227d1b7b1ea2b86a2b8c9 as a separate PR as it's an unrelated functionality and seemingly even more of a bug fix.

What are the examples when `wm_instance` can be useful? `app_id` and `data` are both standard keys for ActivityWatch so they are used for stats and charts, and class in `wm_class` seems the most appropriate for the role as it's set by the app's author.

**Comment by powellnorma** [comment]
> What are the examples when wm_instance can be useful? app_id and data are both standard keys for ActivityWatch so they are used for stats and charts, and class in wm_class seems the most appropriate for the role as it's set by the app's author.

It can be useful as the user can often set it itself, and it can be used to e.g. distinguish different browser instances (using different data-dir etc)
Also, those other attributes don't go away! :)


> I think it would be better to have https://github.com/2e3s/awatcher/commit/9daebc85c0f81c4e450227d1b7b1ea2b86a2b8c9 as a separate PR as it's an unrelated functionality and seemingly even more of a bug fix.

I thought of that but its already based on the first commit, would like to avoid having to backport it if possible?

**Comment by 2e3s** [comment]
> Ok I opened another PR https://github.com/2e3s/awatcher/pull/30 - it is based upon this one, though

Thank you, but I think it's vice versa, the proposed functionality (not sure about it yet) needs to be based on the bug fix which more certainly should be merged.

**Comment by powellnorma** [comment]
> Thank you, but I think it's vice versa, the proposed functionality (not sure about it yet)

Why are you not sure about this yet? Are there any downsides that I am missing?

**Comment by 2e3s** [comment]
One is that it creeps into the interface, I think it's better to make an optional map of extra data to `send_active_window` instead of an extra function `send_active_window_with_instance` for X11.

**Comment by powellnorma** [comment]
> optional map of extra data

You mean like a `extra_data: Option<HashMap<String, String>>` ?
Would it make sense to have this for a new method like `send_active_window_with_extra`, or should we adjust existing client (watcher using `send_active_window`) code?

**Comment by 2e3s** [comment]
> You mean like a extra_data: Option<HashMap<String, String>> ?

Yes.

> Would it make sense to have this for a new method `send_active_window_with_extra`

Yes, with `send_active_window` calling it, it seems the easiest way for the moment. Basically, same as you suggested, but not coupled to X11.

**Comment by 2e3s** [comment]
I also thought about a configurable choice between wm_instance and wm_class for `title` instead of the extra variable, e.g. with replacements in `filters` configuration. Then it can be utilized in UI. But it's a separate improvement.

**Comment by powellnorma** [comment]
I adjusted the code

**Comment by 2e3s** [comment]
Thanks, one small thing left to do, please run `cargo fmt` and push the change

**Comment by powellnorma** [comment]
Done! :)

**Pull request merged**
