### PR TITLE
Bump aw-server-rust

### PR DESCRIPTION
**Pull request by wojnilowicz**
Please test before merging. I only tested the unbundled version.

### CODE REVIEW

**Comment by 2e3s** [comment]
Thanks! I will make further adjustments

**Comment by wojnilowicz** [comment]
Thanks. I see that you went with your own fork of ActivityWatch. That's bad for me, because I couldn't bump it again. Secondly, I bumped it because I would like to package it for Fedora and wanted to use official (also packaged by me) and the latest (requirement of Fedora packaging) aw-server-rust package to build your watcher. 

Did you fork because you're going to diverge from the original ActivityWatch?

**Comment by 2e3s** [comment]
I temporarily referred my fork to test it out in CI before releasing (postponed to figure out probable issues in #23). I have [returned it back](https://github.com/2e3s/awatcher/commit/214ff1c06ee6441a0bd01de08bf5d4979dc79dd6) after my fix was merged in https://github.com/ActivityWatch/aw-server-rust/pull/484

**Comment by 2e3s** [comment]
But even if I use a patched fork for awatcher, I don't think it would make any problem for you and the binaries distribution. The build will take whatever dependencies it needs, it doesn't conflict with the aw-server-rust. For Cargo, `2e3s/aw-server-rust` and `ActivityWatch/aw-server-rust` are different codebases.

**Comment by wojnilowicz** [comment]
> But even if I use a patched fork for awatcher, I don't think it would make any problem for you and the binaries distribution. The build will take whatever dependencies it needs, it doesn't conflict with the aw-server-rust. For Cargo, `2e3s/aw-server-rust` and `ActivityWatch/aw-server-rust` are different codebases.

I'm not sure what you mean, but in order to package it in Fedora, I have to prepackage every dependency of it. Rust (and other) dependencies are not downloaded from the internet but from local repository. If you would make your own fork then I would have to package it as a separate package (and separate to the official on at ActivityWatch) as well. At least in theory.

Anyway, thanks for returning to the official ActivityWatch source. It's always easier to follow upstream.

**Comment by 2e3s** [comment]
> but in order to package it in Fedora, I have to prepackage every dependency of it

All of this https://github.com/2e3s/awatcher/blob/main/watchers/Cargo.toml#L17 is just crates/libraries: aw-client-rust, wayland-client, x11rb, zbus, toml, log, etc, which are downloaded from crates.io or directly from git in order to be built. Not sure about the process, if Fedora's is like [Debian's](https://wiki.debian.org/Rust) then it would be very problematic. So either you're doing a ton of work as a maintainer to keep up all related `librust-{crate}-dev` and alike, or maybe there is some misunderstanding :slightly_smiling_face:

**Comment by wojnilowicz** [comment]
Fedora is like Debian in this matter.

**Pull request merged**
